name:                parallel-polyamory
version:             1.0
github:              "islaterm/parallel-polyamory"
license:             OtherLicense
author:              "Ignacio Slater"
maintainer:          "ignacio.slater@ug.uchile.com"
copyright:           "2020 Ignacio Slater"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/islaterm/parallel-polyamory#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  parallel-polyamory-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - parallel-polyamory
